#! /bin/sh
### BEGIN INIT INFO
# Provides:          edge
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run /etc/rc.local if it exist
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions


case "$1" in
    start)
	/usr/sbin/edge  -d gianluca -a 10.6.6.20 -c studio -k sasso2015 -l bizzarrone.duckdns.org:7000
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
